favicon: /img/favicon.png
avatar: /img/avatar.jpg
# if author sets in hexo_config, this str doesn't work
author: 'Jason'
author_bio: 'Your biography can be writed down here.'

since: 2020

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  Publications: /#Publications
  About: /
  Blog: /

# Don't Change
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  fa fa-twitter: /
  fa fa-facebook-square: /
  fa fa-github: /
  fa fa-stack-overflow: /
  fa fa-linkedin-square: /
  fa fa-weibo: /
  fa fa-wechat: /
  fa fa-qq: /
  fa fa-envelope: / #E-mail
  fa fa-rss: /  #rss

# Additional social_links，不需要的链接直接注释掉
# name: url
e_social:
  enable: true
e_social_links:
  Google Scholar: /
  ORCID: /

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV.pdf
  description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - /js/main.js